"""empty message

Revision ID: 373234ee0473
Revises: a2c1332bcf46
Create Date: 2022-09-04 13:07:26.158122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373234ee0473'
down_revision = 'a2c1332bcf46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
